drop table if exists basicincident;

create table if not exists basicincident(
	state char(2),
	fdid char(5),
	incident_date date,
	incident_number char(7),
	exposure_number integer,
	version char(5),
	department_station char(3),
	incident_type char(3),
	address_wildland_flag char(1),
	mutual_aid char(1),
	alarm_date timestamp,
	arrival_time timestamp,
	under_control_time timestamp,
	last_unit_clear_time timestamp,
	shift char(1),
	alarms char(2),
	district char(3),
	action_taken_1 char(2),
	action_taken_2 char(2),
	action_taken_3 char(2),
	app_module_used char(1),
	suppress_apparatus integer,
	ems_apparatus integer,
	other_apparatus integer,
	supression_personnel integer,
	ems_personnel integer,
	other_personnel integer,
	resources_inc_mutual_aid boolean,
	property_loss integer,
	contents_loss integer,
	property_value integer,
	contents_value integer,
	ff_death integer,
	other_fire_death integer,
	ff_injury integer,
	other_fire_injury integer,
	detector_alerted_occ boolean,
	hazmat_released boolean,
	mixed_use char(2),
	property_use char(3),
	census_tract char(6)
);

